language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

addons:
  apt:
    packages:
    - graphicsmagick
    - libgraphicsmagick1-dev

env:
  matrix:
    -

matrix:
  include:
    - php: 5.6
      env:
        - PHPCS=1
  allow_failures:
    - php: 5.6
      env:
        - PHPCS=1
    - php: hhvm

before_install:
  - uname -a
  - date

install:
  - |
    if [[ "$PHPCS" != 1 ]] && [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then
      pear config-set preferred_state beta;
      pecl channel-update pecl.php.net;
      if [[ $TRAVIS_PHP_VERSION == '7.1' ]] || [[ $TRAVIS_PHP_VERSION == '7.0' ]] ; then
        printf "\n" | pecl install gmagick;
        printf "\n" | pecl install imagick;
      elif [[ $TRAVIS_PHP_VERSION == '5.3' ]] ; then
        printf "\n" | pecl install gmagick-1.1.7RC3;
        printf "\n" | pecl install imagick-2.3.0;
      else
        printf "\n" | pecl install gmagick-1.1.7RC3;
        printf "\n" | pecl install imagick;
      fi;
    fi;

before_script:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install
  - phpenv rehash

script:
  - if [[ "$PHPCS" == 1 ]]; then ./vendor/bin/phpcs --standard=psr2 lib/ tests/; exit $?; fi;
  - ./vendor/phpunit/phpunit/phpunit -c tests --coverage-text --verbose

notifications:
  email: false

